{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kama.clusterScopedName" . }}-manager
  labels:
    {{- include "kama.labels" . | nindent 4 }}
    kama.tannerburns.github.io/release-namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kama.clusterScopedName" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "kama.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
